
import type { Creature } from '@/types';

export const initialCreatures: Creature[] = [
  {
    id: 5,
    name: "Mossling",
    type: "Terra",
    hp: 60,
    maxHp: 60,
    attack: 40,
    defense: 65,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/wDNvtFI.png",
    aiHint: "mossy rock creature",
    lore: "Born from ancient, moss-covered stones, Mosslings are shy creatures that prefer the quiet solitude of deep forests. They can remain motionless for days, appearing as simple rocks to unsuspecting travelers. Their tough, bark-like skin provides excellent natural defense.",
    abilities: [
      { name: "Vine Whip", type: "attack", power: 25, description: "Lashes out with a thorny vine.", energyCost: 15 },
      { name: "Harden", type: "defense", defenseBoost: 15, description: "Tenses its body to raise defense.", energyCost: 20 },
      { name: "Absorb", type: "heal", power: 15, description: "Drains a small amount of HP from the foe.", energyCost: 25 }
    ]
  },
  {
    id: 6,
    name: "Spark-fin",
    type: "Aqua",
    hp: 45,
    maxHp: 45,
    attack: 50,
    defense: 40,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/5lsrqGC.png",
    aiHint: "electric fish",
    lore: "This energetic fish generates a weak electrical field that causes its fins to sparkle with light. They travel in schools, creating dazzling underwater light shows during migrations. While not powerful individually, a large group can generate a significant current.",
    abilities: [
      { name: "Water Gun", type: "attack", power: 22, description: "Squirts a jet of water.", energyCost: 15 },
      { name: "Charge", type: "buff", description: "Gathers electricity to boost the next attack.", energyCost: 20 },
      { name: "Splash", type: "debuff", description: "A useless splash that distracts the opponent.", energyCost: 10 }
    ]
  },
  {
    id: 7,
    name: "Aero-ling",
    type: "Aero",
    hp: 50,
    maxHp: 50,
    attack: 55,
    defense: 35,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/rnfuT9c.png",
    aiHint: "small wind spirit",
    lore: "Aero-lings are playful spirits of the wind, often seen chasing leaves on breezy autumn days. They are incredibly light, with hollow bones and bodies composed partially of condensed air. Despite their small size, they can be fiercely territorial, defending their nests with sharp pecks and gusts of wind.",
    abilities: [
      { name: "Peck", type: "attack", power: 28, description: "A quick, sharp peck.", energyCost: 15 },
      { name: "Screech", type: "debuff", description: "A loud screech that lowers opponent's defense.", energyCost: 20 },
      { name: "Quick Attack", type: "attack", power: 20, description: "A speedy charge that always strikes first.", energyCost: 15 }
    ]
  }
];

const regularOpponents: Creature[] = [
  {
    id: 21,
    name: "Stoneling",
    type: "Terra",
    hp: 55,
    maxHp: 55,
    attack: 45,
    defense: 60,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/JhdPtwJ.png",
    aiHint: "rock golem",
    lore: "Stonelings are often mistaken for inanimate boulders until they rise from the earth to defend their territory. Their bodies are composed of granite and sediment, making them incredibly sturdy but slow-moving. They communicate through low, rumbling sounds that vibrate through the ground.",
    abilities: [
      { name: "Rock Throw", type: "attack", power: 20, description: "Hurls a small rock.", energyCost: 15 },
      { name: "Stone Skin", type: "defense", defenseBoost: 10, description: "Hardens skin, increasing defense.", energyCost: 20 },
      { name: "Tremor", type: "attack", power: 30, description: "A lesser ground-shaking attack.", energyCost: 25 }
    ]
  },
  {
    id: 22,
    name: "Aqua-pup",
    type: "Aqua",
    hp: 45,
    maxHp: 45,
    attack: 55,
    defense: 40,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/R2bg0hY.png",
    aiHint: "water wolf",
    lore: "These playful creatures are the spirits of mountain streams, with fur that mimics the flow of water. Aqua-pups are known for their loyalty and will fiercely protect the riverbeds they call home. They hunt in small packs, using coordinated underwater maneuvers to confuse their prey.",
    abilities: [
        { name: "Bite", type: "attack", power: 22, description: "A sharp, quick bite.", energyCost: 15 },
        { name: "Aqua Jet", type: "attack", power: 18, description: "Slam into the foe with high speed.", energyCost: 20 },
        { name: "Soothing Mist", type: 'heal', power: 15, description: 'Heals some HP.', energyCost: 30 }
    ]
  },
  {
    id: 23,
    name: "Fetheray",
    type: "Aero",
    hp: 40,
    maxHp: 40,
    attack: 50,
    defense: 35,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/UNuMqjq.png",
    aiHint: "airborne manta",
    lore: "Fetherays gracefully ride the thermal updrafts of canyons and mountains, rarely touching the ground. Their bodies are light and flexible, allowing them to perform complex aerial acrobatics. Sailors consider a Fetheray sighting to be a good omen, signaling fair winds and clear skies.",
    abilities: [
        { name: "Gust", type: "attack", power: 25, description: "A quick blast of wind.", energyCost: 15 },
        { name: "Tailwind", type: "buff", description: "Raises speed for a few turns.", energyCost: 20 },
        { name: "Air Cutter", type: "attack", power: 32, description: "A sharp blade of wind.", energyCost: 25 }
    ]
  },
    {
    id: 24,
    name: "Ember-kit",
    type: "Ignis",
    hp: 50,
    maxHp: 50,
    attack: 65,
    defense: 40,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/Cf0ftUv.png",
    aiHint: "fire fox",
    lore: "The fur of an Ember-kit smolders with a gentle warmth, and its tail burns with a flame that reflects its health and mood. They are mischievous creatures, often found playfully chasing fireflies at dusk. An Ember-kit's flame can flare up dramatically when it is angered or threatened.",
    abilities: [
        { name: "Scratch", type: "attack", power: 20, description: "A basic scratch attack.", energyCost: 10 },
        { name: "Flame Wheel", type: "attack", power: 35, description: "A fiery spinning tackle.", energyCost: 25 },
        { name: "Will-O-Wisp", type: "debuff", description: "Lowers the opponent's attack.", energyCost: 20 }
    ]
  },
  {
    id: 25,
    name: "Glimmerwisp",
    type: "Lux",
    hp: 60,
    maxHp: 60,
    attack: 30,
    defense: 50,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/kvQo9oc.png",
    aiHint: "light spirit",
    lore: "These benevolent spirits are living embodiments of soft light, often found in sacred groves and ancient ruins. A Glimmerwisp's light is said to have healing properties and can soothe troubled minds. They are drawn to acts of kindness and may guide lost travelers to safety.",
    abilities: [
        { name: "Flash", type: "debuff", description: "Lowers opponent's accuracy.", energyCost: 15 },
        { name: "Light Screen", type: "defense", defenseBoost: 25, description: "A screen of light that boosts defense.", energyCost: 30 },
        { name: "Heal Pulse", type: "heal", power: 25, description: "Heals for a small amount.", energyCost: 30 }
    ]
  },
  {
    id: 26,
    name: "Shade-crawler",
    type: "Umbra",
    hp: 48,
    maxHp: 48,
    attack: 58,
    defense: 48,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/MVcAOcy.png",
    aiHint: "shadow spider",
    lore: "Shade-crawlers thrive in the darkest caves and deepest shadows, their bodies absorbing the surrounding light. They spin webs of pure darkness that are nearly impossible to see, trapping unsuspecting prey. Despite their fearsome appearance, they are ambush predators that prefer to hide.",
    abilities: [
        { name: "Poison Sting", type: "attack", power: 25, description: "A venomous jab.", energyCost: 20 },
        { name: "Shadow Sneak", type: "attack", power: 30, description: "Attacks from the shadows.", energyCost: 25 },
        { name: "Fade", type: "defense", defenseBoost: 18, description: "Fades into the darkness, raising defense.", energyCost: 20 }
    ]
  },
  {
    id: 27,
    name: "Sunstone Turtle",
    type: "Lux",
    hp: 70,
    maxHp: 70,
    attack: 35,
    defense: 80,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/JDrtGtD.jpg",
    aiHint: "glowing stone turtle",
    lore: "The shell of a Sunstone Turtle is embedded with luminous crystals that absorb and store sunlight. They spend their days basking, and at night their shells emit a warm, gentle glow. Ancient legends claim their shells can focus light into powerful defensive barriers.",
    abilities: [
        { name: "Shell Smash", type: "attack", power: 30, description: "A powerful body slam.", energyCost: 20 },
        { name: "Solar Beam", type: "attack", power: 45, description: "A concentrated blast of light.", energyCost: 35 },
        { name: "Iron Defense", type: "defense", defenseBoost: 20, description: "Hardens its shell to the max.", energyCost: 25 }
    ]
  },
  {
    id: 28,
    name: "Gloomfang",
    type: "Umbra",
    hp: 55,
    maxHp: 55,
    attack: 65,
    defense: 45,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/AZa9NFC.jpg",
    aiHint: "shadow wolf beast",
    lore: "A hunter of the twilight hours, the Gloomfang stalks the edges of dark forests. Its fur is the color of a moonless night, allowing it to blend seamlessly into the shadows. The eerie howl of a Gloomfang is said to drain the courage from even the bravest warriors.",
    abilities: [
        { name: "Shadow Claw", type: "attack", power: 35, description: "Slashes with claws of darkness.", energyCost: 20 },
        { name: "Howl", type: "buff", description: "A chilling howl that raises attack.", energyCost: 15 },
        { name: "Bite", type: "attack", power: 25, description: "A standard, vicious bite.", energyCost: 15 }
    ]
  },
  {
    id: 29,
    name: "Vine-Crawler",
    type: "Terra",
    hp: 65,
    maxHp: 65,
    attack: 50,
    defense: 55,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/Tu19ubc.jpg",
    aiHint: "sentient vine monster",
    lore: "A creature born from the dense, magical undergrowth of ancient forests. The Vine-Crawler can command the plants around it, using them to entangle foes and absorb nutrients directly from the soil. Its central body is a hardened knot of wood, protecting a glowing, life-giving core.",
    abilities: [
        { name: "Leech Seed", type: "heal", power: 15, description: "Saps opponent's HP each turn.", energyCost: 25 },
        { name: "Razor Leaf", type: "attack", power: 30, description: "Slices with sharp-edged leaves.", energyCost: 20 },
        { name: "Camouflage", type: "defense", defenseBoost: 20, description: "Blends in to raise defense.", energyCost: 20 }
    ]
  },
  {
    id: 30,
    name: "Geyser-Fin",
    type: "Aqua",
    hp: 50,
    maxHp: 50,
    attack: 65,
    defense: 45,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/hLE6886.jpg",
    aiHint: "geyser fish",
    lore: "Geyser-Fins make their homes in volcanically active waters, absorbing geothermal energy. They can store immense pressure within their bodies, releasing it in powerful, targeted blasts of boiling water. The temperature of the water they shoot can be hot enough to melt rock.",
    abilities: [
        { name: "Scald", type: "attack", power: 38, description: "Shoots boiling water.", energyCost: 25 },
        { name: "Aqua Ring", type: "heal", power: 20, description: "Restores a little HP each turn.", energyCost: 30 },
        { name: "Dive", type: "attack", power: 35, description: "Dives then strikes on the next turn.", energyCost: 25 }
    ]
  },
  {
    id: 31,
    name: "Zephyr-Wisp",
    type: "Aero",
    hp: 45,
    maxHp: 45,
    attack: 68,
    defense: 40,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/CkZd9xC.jpg",
    aiHint: "glowing wind spirit",
    lore: "A more potent and focused version of an Aero-ling, the Zephyr-Wisp is a being of pure, rushing wind. It moves with incredible speed, appearing as little more than a blur to the naked eye. They are said to be the messengers of the great wind titans, carrying whispers on the breeze.",
    abilities: [
        { name: "Twister", type: "attack", power: 35, description: "Whips up a vicious twister.", energyCost: 25 },
        { name: "Agility", type: "buff", description: "Greatly raises its speed.", energyCost: 15 },
        { name: "Feather Dance", type: "debuff", description: "Lowers the opponent's attack.", energyCost: 20 }
    ]
  },
  {
    id: 32,
    name: "Magma-Pup",
    type: "Ignis",
    hp: 60,
    maxHp: 60,
    attack: 60,
    defense: 60,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/t7e7Gqq.jpg",
    aiHint: "magma puppy",
    lore: "These sturdy creatures have bodies of cooling magma, with a fiery core that never extinguishes. Magma-Pups are surprisingly playful, often chasing rolling boulders down volcanic slopes. Their bark sounds like the crackling of a powerful fire, and their bite can melt steel.",
    abilities: [
        { name: "Lava Plume", type: "attack", power: 40, description: "A blast of lava.", energyCost: 30 },
        { name: "Rock Polish", type: "buff", description: "Boosts its speed.", energyCost: 15 },
        { name: "Eruption", type: "attack", power: 50, description: "A powerful volcanic eruption.", energyCost: 35 }
    ]
  },
  {
    id: 33,
    name: "Celestial-Kirin",
    type: "Lux",
    hp: 70,
    maxHp: 70,
    attack: 50,
    defense: 65,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/gAFahTr.jpg",
    aiHint: "divine unicorn beast",
    lore: "A sacred beast said to be born from a fallen star. The Celestial-Kirin is a bringer of peace and prosperity, and its presence can cause barren lands to bloom with life. Its horn glows with a holy light that can mend wounds and purify corruption.",
    abilities: [
        { name: "Holy Light", type: "heal", power: 30, description: "Bathes in holy light to heal.", energyCost: 30 },
        { name: "Horn Drill", type: "attack", power: 45, description: "A powerful, focused horn attack.", energyCost: 30 },
        { name: "Mystic Veil", type: "defense", defenseBoost: 25, description: "A magical veil boosts defense.", energyCost: 25 }
    ]
  },
  {
    id: 34,
    name: "Granite Golem",
    type: "Terra",
    hp: 85,
    maxHp: 85,
    attack: 65,
    defense: 95,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/WtXTSWA.jpg",
    aiHint: "granite golem beast",
    lore: "An evolution of the Stoneling, the Granite Golem is a massive protector of sacred mountains. Its body is formed from a single, unbroken piece of granite, granting it immense physical and magical resistance. It moves slowly but with unstoppable force, its steps shaking the very ground.",
    abilities: [
      { name: "Fissure", type: "attack", power: 50, description: "Slams the ground, splitting it open.", energyCost: 35 },
      { name: "Body Press", type: "attack", power: 40, description: "A heavy slam using its immense defense.", energyCost: 30 },
      { name: "Rock Tomb", type: "debuff", description: "Traps the opponent, lowering their speed.", energyCost: 20 },
    ],
  },
  {
    id: 35,
    name: "Coral Sentinel",
    type: "Aqua",
    hp: 75,
    maxHp: 75,
    attack: 55,
    defense: 85,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/QC9Te9k.jpg",
    aiHint: "coral reef guardian",
    lore: "Living fortresses of the sea, Coral Sentinels are born from ancient, vibrant reefs. They are slow-moving but incredibly resilient, their bodies providing homes for countless smaller sea creatures. When angered, a Coral Sentinel can command the reef itself to attack intruders.",
    abilities: [
      { name: "Aqua Wall", type: "defense", defenseBoost: 30, description: "Forms a wall of pressurized water.", energyCost: 25 },
      { name: "Spike Cannon", type: "attack", power: 40, description: "Fires sharp coral spikes at the foe.", energyCost: 30 },
      { name: "Recover", type: "heal", power: 30, description: "Regenerates part of its coral body.", energyCost: 35 },
    ],
  },
  {
    id: 36,
    name: "Storm Strider",
    type: "Aero",
    hp: 65,
    maxHp: 65,
    attack: 80,
    defense: 50,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/0Fj99r8.jpg",
    aiHint: "lightning bird creature",
    lore: "These magnificent birds live within thunderclouds, and are said to be born from lightning strikes. A Storm Strider's feathers crackle with static electricity, and it can move as fast as the lightning it commands. They are rarely seen, only appearing during the most intense storms.",
    abilities: [
      { name: "Thunderbolt", type: "attack", power: 55, description: "A powerful bolt of lightning strikes the foe.", energyCost: 35 },
      { name: "Feather Dance", type: "debuff", description: "Lowers the opponent's attack sharply.", energyCost: 20 },
      { name: "Roost", type: "heal", power: 25, description: "Lands to rest and recover HP.", energyCost: 30 },
    ],
  },
  {
    id: 37,
    name: "Cinderclaw",
    type: "Ignis",
    hp: 70,
    maxHp: 70,
    attack: 90,
    defense: 60,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/KifucpY.jpg",
    aiHint: "volcanic lizard beast",
    lore: "Cinderclaws are ferocious predators that make their lairs in volcanic vents. Their scales are superheated obsidian, and their claws can slice through rock. They are aggressive and territorial, using their fiery breath to hunt and to warn away rivals from their territory.",
    abilities: [
      { name: "Flare Blitz", type: "attack", power: 60, description: "A reckless, full-body fire tackle.", energyCost: 40 },
      { name: "Scary Face", type: "debuff", description: "Intimidates the foe to lower their speed.", energyCost: 15 },
      { name: "Fire Fang", type: "attack", power: 45, description: "A bite attack wreathed in flames.", energyCost: 30 },
    ],
  },
  {
    id: 38,
    name: "Rune-Bear",
    type: "Terra",
    hp: 90,
    maxHp: 90,
    attack: 80,
    defense: 70,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/gH9DiQx.jpg",
    aiHint: "glowing rune bear",
    lore: "Ancient bears that hibernate for centuries, their fur becoming covered in glowing, moss-like runes. The runes grant the Rune-Bear mystical powers, allowing it to channel the earth's energy. When awoken, they are grumpy but powerful guardians of the forest's oldest secrets.",
    abilities: [
      { name: "Ancient Power", type: "buff", description: "A primal force that may boost all stats.", energyCost: 30 },
      { name: "Bear Hug", type: "attack", power: 50, description: "A crushing hug that deals heavy damage.", energyCost: 35 },
      { name: "Rest", type: "heal", power: 50, description: "Recovers HP but falls asleep for a turn.", energyCost: 25 },
    ],
  },
  {
    id: 39,
    name: "Dream-Weaver",
    type: "Lux",
    hp: 70,
    maxHp: 70,
    attack: 60,
    defense: 75,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/Tk3I3ZG.jpg",
    aiHint: "celestial moth",
    lore: "A mystical moth whose scales shimmer with the light of distant stars. The dust from a Dream-Weaver's wings can induce vivid dreams or terrifying nightmares. They are elusive, nocturnal creatures that feed on moonlight and are said to be manifestations of the collective unconscious.",
    abilities: [
      { name: "Moonbeam", type: "attack", power: 50, description: "A concentrated blast of moonlight.", energyCost: 30 },
      { name: "Hypnosis", type: "debuff", description: "A sleep-inducing pattern of light.", energyCost: 25 },
      { name: "Starlight Heal", type: "heal", power: 35, description: "Uses starlight to slowly recover HP.", energyCost: 30 },
    ],
  },
  {
    id: 40,
    name: "Abyss-Watcher",
    type: "Umbra",
    hp: 80,
    maxHp: 80,
    attack: 75,
    defense: 75,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/A165Zo2.jpg",
    aiHint: "deep sea octopus",
    lore: "This intelligent cephalopod dwells in the crushing pressure of the deepest oceanic trenches. Its body is made of solidified shadow and bioluminescent ink. An Abyss-Watcher can manipulate darkness to ensnare its prey and create illusions to confuse its enemies.",
    abilities: [
      { name: "Ink Jet", type: "debuff", description: "Blinds the opponent, lowering their accuracy.", energyCost: 20 },
      { name: "Abyssal Grasp", type: "attack", power: 55, description: "Tendrils of shadow constrict the foe.", energyCost: 35 },
      { name: "Dark Pulse", type: "attack", power: 45, description: "An aura of dark energy is released.", energyCost: 30 },
    ],
  },
  {
    id: 41,
    name: "Mirage-Cat",
    type: "Aero",
    hp: 68,
    maxHp: 68,
    attack: 85,
    defense: 60,
    energy: 100,
    maxEnergy: 100,
    imageUrl: "https://i.imgur.com/7J9VKGj.jpg",
    aiHint: "sand cat spirit",
    lore: "A mystical feline that is born from desert heat hazes and shimmering sands. The Mirage-Cat moves with silent grace, its form wavering like a trick of the light, making it incredibly difficult to hit. It is a cunning hunter that uses its illusory nature to stalk prey across the dunes.",
    abilities: [
      { name: "Sandstorm", type: "attack", power: 40, description: "Whips up a blinding sandstorm.", energyCost: 25 },
      { name: "Double Team", type: "defense", defenseBoost: 20, description: "Creates illusory copies to boost defense.", energyCost: 20 },
      { name: "Phantom Claw", type: "attack", power: 50, description: "A swift slash that seems to pass through defenses.", energyCost: 30 },
    ],
  },
];

const bossCreatures: Creature[] = [
    {
    id: 101,
    name: "Terralord",
    type: "Terra",
    hp: 150,
    maxHp: 150,
    attack: 75,
    defense: 90,
    energy: 120,
    maxEnergy: 120,
    imageUrl: "https://i.imgur.com/eDm0sH8.png",
    aiHint: "earth titan",
    lore: "The Terralord is an ancient guardian of the mountains, awoken from a thousand-year slumber. Its body is formed from the very bedrock of the world, making its defense nearly impenetrable. Legends say that when the Terralord moves, entire mountain ranges are born.",
    abilities: [
        { name: "Tackle", type: "attack", power: 40, description: "A basic tackle.", energyCost: 15 },
        { name: "Fortify", type: "defense", defenseBoost: 25, description: "Greatly raises defense.", energyCost: 25 },
        { name: "Earthquake", type: "attack", power: 60, description: "A devastating ground-shaking attack.", energyCost: 40 }
    ]
  },
  {
    id: 102,
    name: "Abyssal Leviathan",
    type: "Aqua",
    hp: 140,
    maxHp: 140,
    attack: 80,
    defense: 70,
    energy: 120,
    maxEnergy: 120,
    imageUrl: "https://i.imgur.com/1hWZRTh.png",
    aiHint: "giant sea-dragon",
    lore: "This colossal beast slumbers in the deepest trenches of the ocean, its movements causing the tides to shift. The Abyssal Leviathan's scales shimmer with the colors of the deep, and its roar is the sound of a tidal wave. It is the undisputed ruler of the seas.",
    abilities: [
        { name: "Tidal Wave", type: "attack", power: 45, description: "A huge wave crashes down.", energyCost: 25 },
        { name: "Regenerate", type: "heal", power: 30, description: "Recovers a good amount of HP.", energyCost: 30 },
        { name: "Dragon Pulse", type: "attack", power: 55, description: "A powerful draconic blast.", energyCost: 35 }
    ]
  },
  {
    id: 103,
    name: "Thunder-roc",
    type: "Aero",
    hp: 130,
    maxHp: 130,
    attack: 85,
    defense: 65,
    energy: 120,
    maxEnergy: 120,
    imageUrl: "https://i.imgur.com/yPVjvwQ.png",
    aiHint: "giant thunder-bird",
    lore: "The Thunder-roc is a legendary bird whose wingspan can blot out the sun, creating unnatural storms. It nests on the highest, most inaccessible peaks, and its feathers crackle with static electricity. It is said that a single flap of its wings can create a hurricane.",
    abilities: [
        { name: "Drill Peck", type: "attack", power: 50, description: "A powerful, spinning beak attack.", energyCost: 25 },
        { name: "Thunder", type: "attack", power: 65, description: "A massive bolt of lightning.", energyCost: 40 },
        { name: "Roost", type: "heal", power: 25, description: "Recovers some HP.", energyCost: 30 }
    ]
  },
  {
    id: 104,
    name: "Inferno Cerberus",
    type: "Ignis",
    hp: 135,
    maxHp: 135,
    attack: 95,
    defense: 60,
    energy: 120,
    maxEnergy: 120,
    imageUrl: "https://i.imgur.com/vTn5Xqb.png",
    aiHint: "three-headed fire-hound",
    lore: "This monstrous three-headed hound guards the gates to the planet's molten core. Each of its heads can breathe a different type of flame, from scorching heat to soul-chilling black fire. The Inferno Cerberus is a relentless attacker that will stop at nothing to incinerate its foes.",
    abilities: [
        { name: "Scorching Bite", type: "attack", power: 50, description: "A vicious, fiery bite.", energyCost: 25 },
        { name: "Howl", type: "buff", description: "Raises its own attack stat.", energyCost: 15 },
        { name: "Hellfire", type: "attack", power: 70, description: "Engulfs the foe in black flames.", energyCost: 45 }
    ]
  },
  {
    id: 105,
    name: "Chrono-Wing",
    type: "Lux",
    hp: 200,
    maxHp: 200,
    attack: 85,
    defense: 85,
    energy: 150,
    maxEnergy: 150,
    imageUrl: "https://i.imgur.com/98DLelJ.jpg",
    aiHint: "clockwork dragon",
    lore: "A being that exists outside the normal flow of time, the Chrono-Wing is a paradox of metal and light. Its clockwork body moves with impossible precision, and its wings beat to a rhythm only it can hear. It is said to be the guardian of history, capable of rewinding time to heal its wounds or replaying attacks.",
    abilities: [
        { name: "Time Rift", type: "attack", power: 60, description: "Tears a hole in time to strike.", energyCost: 35 },
        { name: "Stasis Field", type: "debuff", description: "May cause the opponent to lose a turn.", energyCost: 40 },
        { name: "Temporal Heal", type: "heal", power: 50, description: "Reverts its own wounds by rewinding time.", energyCost: 45 }
    ]
  },
  {
    id: 106,
    name: "Void-Reaver",
    type: "Umbra",
    hp: 180,
    maxHp: 180,
    attack: 105,
    defense: 75,
    energy: 140,
    maxEnergy: 140,
    imageUrl: "https://i.imgur.com/yxRhD2k.jpg",
    aiHint: "eldritch void monster",
    lore: "The Void-Reaver is an alien entity that slipped through a crack between dimensions. It is a being of pure hunger, consuming all light and matter it comes into contact with. Its amorphous body shifts and writhes, making it a terrifying and unpredictable opponent.",
    abilities: [
        { name: "Abyssal Grasp", type: "attack", power: 65, description: "Tendrils of shadow lash out.", energyCost: 35 },
        { name: "Consume Light", type: "heal", power: 40, description: "Drains life from the opponent.", energyCost: 40 },
        { name: "Oblivion", type: "attack", power: 80, description: "A blast of pure void energy.", energyCost: 50 }
    ]
  },
  {
    id: 107,
    name: "Nexus-Guardian",
    type: "Terra",
    hp: 250,
    maxHp: 250,
    attack: 90,
    defense: 100,
    energy: 200,
    maxEnergy: 200,
    imageUrl: "https://i.imgur.com/W1meE1j.jpg",
    aiHint: "elemental crystal titan",
    lore: "The final guardian of Terraverse, the Nexus-Guardian is the living embodiment of all elements in harmony. It was created at the beginning of time to maintain the world's balance. Its crystal body pulses with unimaginable power, capable of unleashing attacks of every elemental type.",
    abilities: [
        { name: "Prismatic Wave", type: "attack", power: 70, description: "Unleashes a wave of mixed elemental energy.", energyCost: 40 },
        { name: "Elemental Shift", type: "defense", defenseBoost: 40, description: "Changes its resistance by shifting elements.", energyCost: 30 },
        { name: "Core Eruption", type: "attack", power: 90, description: "The ultimate elemental blast.", energyCost: 60 }
    ]
  },
  {
    id: 108,
    name: "Solaris, the Sun-Phoenix",
    type: "Ignis",
    hp: 220,
    maxHp: 220,
    attack: 110,
    defense: 80,
    energy: 160,
    maxEnergy: 160,
    imageUrl: "https://i.imgur.com/q5COtZo.jpg",
    aiHint: "giant sun phoenix",
    lore: "A legendary phoenix born from the sun itself, Solaris is a being of pure, unending fire. Its wingspan creates brilliant auroras, and its cry is the sound of a solar flare. It is said that when Solaris is defeated, it is reborn from its own ashes, stronger than before.",
    abilities: [
      { name: "Supernova", type: "attack", power: 85, description: "An explosive blast of solar energy.", energyCost: 55 },
      { name: "Rebirth", type: "heal", power: 70, description: "Heals a massive amount of HP one time.", energyCost: 60 },
      { name: "Sun's Grace", type: "buff", description: "Boosts all stats for a few turns.", energyCost: 40 },
    ],
  },
  {
    id: 109,
    name: "Nocturne, the Shadow Titan",
    type: "Umbra",
    hp: 260,
    maxHp: 260,
    attack: 100,
    defense: 110,
    energy: 150,
    maxEnergy: 150,
    imageUrl: "https://i.imgur.com/9bXMvx7.jpg",
    aiHint: "colossal shadow titan",
    lore: "A colossal titan forged from the absence of light and the fear of the dark. Nocturne's form is ever-changing, a mass of shadows and chilling whispers. It feeds on despair and can trap its foes in a realm of eternal twilight, draining their will to fight.",
    abilities: [
      { name: "Nightfall", type: "attack", power: 75, description: "Plunges the battlefield into darkness, damaging the foe.", energyCost: 50 },
      { name: "Shadow Wall", type: "defense", defenseBoost: 50, description: "A barrier of solid shadow.", energyCost: 40 },
      { name: "Soul Drain", type: "heal", power: 60, description: "Drains a significant amount of life from the foe.", energyCost: 50 },
    ],
  },
];

export const opponentCreatures: Creature[] = [
  ...regularOpponents,
  ...bossCreatures,
];
