import type { Creature } from '@/types';

export const initialCreatures: Creature[] = [
  {
    id: 1,
    name: "Stoneling",
    type: "Terra",
    hp: 55,
    maxHp: 55,
    attack: 45,
    defense: 60,
    speed: 30,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "rock golem",
  },
  {
    id: 2,
    name: "Aqua-pup",
    type: "Aqua",
    hp: 45,
    maxHp: 45,
    attack: 55,
    defense: 40,
    speed: 50,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "water wolf",
  },
  {
    id: 3,
    name: "Fetheray",
    type: "Aero",
    hp: 40,
    maxHp: 40,
    attack: 50,
    defense: 35,
    speed: 70,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "airborne manta",
  },
  {
    id: 4,
    name: "Ember-kit",
    type: "Ignis",
    hp: 50,
    maxHp: 50,
    attack: 65,
    defense: 40,
    speed: 60,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "fire fox",
  },
  {
    id: 5,
    name: "Glimmerwisp",
    type: "Lux",
    hp: 60,
    maxHp: 60,
    attack: 30,
    defense: 50,
    speed: 45,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "light spirit",
  },
  {
    id: 6,
    name: "Shade-crawler",
    type: "Umbra",
    hp: 48,
    maxHp: 48,
    attack: 58,
    defense: 48,
    speed: 58,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "shadow spider",
  },
];

export const opponentCreatures: Creature[] = [
    {
    id: 101,
    name: "Cragbeast",
    type: "Terra",
    hp: 70,
    maxHp: 70,
    attack: 55,
    defense: 70,
    speed: 20,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "mountain monster",
  },
  {
    id: 102,
    name: "Sea Serpent",
    type: "Aqua",
    hp: 65,
    maxHp: 65,
    attack: 60,
    defense: 55,
    speed: 60,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "ocean dragon",
  },
  {
    id: 103,
    name: "Stormwing",
    type: "Aero",
    hp: 60,
    maxHp: 60,
    attack: 65,
    defense: 50,
    speed: 80,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "thunder bird",
  },
  {
    id: 104,
    name: "Pyre-hound",
    type: "Ignis",
    hp: 62,
    maxHp: 62,
    attack: 75,
    defense: 50,
    speed: 70,
    imageUrl: "https://placehold.co/300x200.png",
    aiHint: "hell hound",
  },
];
